services:
  db:
    image: postgres:16-alpine         
    container_name: condominio_db 
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
          interval: 5s
          timeout: 3s
          retries: 20

  backend:
    build: ./backend
    container_name: condominio_backend
    env_file: .env
    user: "${UID:-1000}:${GID:-1000}"
    command: /bin/sh -lc "./entrypoint.sh"
    volumes:
      - ./backend:/app
      - backend_static:/app/staticfiles
      - backend_media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: node:20-bookworm
    container_name: condominio_frontend 
    working_dir: /app
    env_file: .env
    volumes:
      - ./web-frontend:/app
      - node_modules_frontend:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    command: >
      sh -lc "if [ ! -x node_modules/.bin/vite ]; then
                if [ -f package-lock.json ]; then
                  npm ci --no-audit --no-fund;
                else
                  npm i --no-audit --no-fund;
                fi;
              fi;
          npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - backend

volumes:
  pgdata:
  backend_static:
  backend_media:
  node_modules_frontend:
