# Generated by Django 5.2.6 on 2025-09-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='horario_apertura',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='horario_cierre',
            field=models.TimeField(default='22:00:00'),
        ),
    ]
