# Generated by Django 5.2.6 on 2025-09-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_areacomun_horario_apertura_areacomun_horario_cierre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacomun',
            name='horario',
        ),
    ]
