# Generated by Django 5.2.6 on 2025-09-13 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_areacomun_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresosalida',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='multa',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_area',
            new_name='area_comun',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='ingresosalida',
            name='extranjero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.extranjero'),
        ),
    ]
